server:
  port: 8080
#  servlet:
#    context-
    #ㄹㅇㅋㅋ
    #프로필사진
    #홍길동
    #분 전
  # 5
  #ㄹㅇㅋㅋpath: /haejwoing

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

<<<<<<< Updated upstream
    url: jdbc:mysql://localhost:3305/haejwoing?serverTimezone=Asia/Seoul
    username: root
    password: wkfkek3730**
=======

    url: jdbc:mysql://localhost:3307/haejwoing?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r@
>>>>>>> Stashed changes


#    url: jdbc:mysql://i6c103.p.ssafy.io/haejwoing
#    username: ha ejwoing
#    password: 1234


mybatis:
  type-aliases-package: com.haejwoing.back.model.dto
  mapper-locations: classpath:mappers/*.xml

