server:
  port: 8080
#  servlet:
#    context-
    #ㄹㅇㅋㅋ
    #프로필사진
    #홍길동
    #분 전
  # 5
  #ㄹㅇㅋㅋpath: /haejwoing

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


    url: jdbc:mysql://localhost:3306/haejwoing?serverTimezone=Asia/Seoul
    username: root
    password: chae6343!@#



#    url: jdbc:mysql://i6c103.p.ssafy.io/haejwoing
#    username: ha ejwoing
#    password: 1234


mybatis:
  type-aliases-package: com.haejwoing.back.model.dto
  mapper-locations: classpath:mappers/*.xml

