server:
  port: 8080
#  servlet:
#    context-path: /haejwoing

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


    url: jdbc:mysql://localhost:3307/haejwoing?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r@


#    url: jdbc:mysql://i6c103.p.ssafy.io/haejwoing
#    username: ha ejwoing
#    password: 1234


mybatis:
  type-aliases-package: com.haejwoing.back.model.dto
  mapper-locations: classpath:mappers/*.xml

