server:
  port: 8080
#  servlet:
#    context-path: /haejwoing

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/haejwoing?serverTimezone=Asia/Seoul
    username: root
    password: wkfkek3730**

#    url: jdbc:mysql://i6c103.p.ssafy.io/haejwoing
#    username: haejwoing
#    password: 1234


mybatis:
  type-aliases-package: com.haejwoing.back.model.dto
  mapper-locations: classpath:mappers/*.xml

